import { Fragment } from "react";

import Head from "next/head";
import Layout from "../layout";
import styles from "./Utssatu.module.scss";

const UtsSatuPage = ({ datas }) => {
  const List = ({ id, name, price }) => {
    return (
      <div className={styles.list}>
        <span>{id}</span>
        <span>{name}</span>
        <span>{price}</span>
      </div>
    );
  };

  return (
    <Fragment>
      <Head>
        <title>UTS 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <div className={styles.card}>
            <h4>JSON Data</h4>
            {datas?.json?.map((dt, index) => (
              <List key={index} id={dt?.Id} name={dt?.Name} price={dt?.Price} />
            ))}
          </div>
          <div className={styles.card}>
            <h4>CSV Data</h4>
            {datas?.csv?.map((dt, index) => (
              <List key={index} id={dt?.Id} name={dt?.Name} price={dt?.Price} />
            ))}
          </div>
          <div className={styles.card}>
            <h4>XML Data</h4>
            {datas?.xml?.map((dt, index) => (
              <List key={index} id={dt?.Id} name={dt?.Name} price={dt?.Price} />
            ))}
          </div>
        </main>
      </Layout>
    </Fragment>
  );
};

export default UtsSatuPage;

export async function getServerSideProps(context) {
  const res = await fetch("http://localhost:3000/api/uts/getall");

  const data = await res.json();

  return {
    props: {
      datas: data,
    },
  };
}
