import { Fragment } from "react";
import querystring from "node:querystring";
import Head from "next/head";
import Form from "../../../components/Form";
import Layout from "../../layout";
import styles from "../index.module.scss";

const UpdatePage = ({ datas }) => {
  return (
    <Fragment>
      <Head>
        <title>Update</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <Form ids={datas.id} ctaName="Update" data={datas} />
        </main>
      </Layout>
    </Fragment>
  );
};

export default UpdatePage;

export async function getServerSideProps(context) {
  const { query } = context;

  if (query?.id?.length !== 2) {
    return {
      notFound: true,
    };
  }

  const queryStr = {
    id: query?.id?.slice(-1),
  };

  const res = await fetch(
    `http://localhost:3000/api/uts/get?${querystring.stringify(queryStr)}`
  );

  const data = await res.json();

  return {
    props: {
      datas: data,
    },
  };
}
