import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.links}>
          <Link href="/utssatu">UTS 1</Link>
          <Link href="/utsdua">UTS 2</Link>
        </div>
      </main>
    </div>
  );
}
